{{- if and (not .Values.mysql.enabled) (not .Values.externalDatabase.existingSecret) .Values.externalDatabase.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}-db-secret
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}

{{- if and (eq .Values.mode "distributed") (not .Values.redis.enabled) (not .Values.externalRedis.existingSecret) .Values.externalRedis.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}-redis-secret
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.externalRedis.password | b64enc | quote }}
{{- end }}
